package main

import (
	"strings"
	"testing"
)

var example = `.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............`

func TestPart1(t *testing.T) {
	if got, want := Part1(strings.NewReader(example)), 21; got != want {
		t.Errorf("got %v, want %v", got, want)
	}
}

func TestPart2(t *testing.T) {
	if got, want := Part2(strings.NewReader(example)), 40; got != want {
		t.Errorf("got %v, want %v", got, want)
	}
}
